// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWJ_QgwLD7BwUd3vwHs0Atwu9ViqaMP8E',
    appId: '1:148500310293:web:ff771184495d40318ea11c',
    messagingSenderId: '148500310293',
    projectId: 'globalidoc-cd69a',
    authDomain: 'globalidoc-cd69a.firebaseapp.com',
    storageBucket: 'globalidoc-cd69a.appspot.com',
    measurementId: 'G-KG60SP88P8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKiKBCsIpElSYwfV9LskT2nBk97iFNDIU',
    appId: '1:148500310293:android:4cff969fc2281b448ea11c',
    messagingSenderId: '148500310293',
    projectId: 'globalidoc-cd69a',
    storageBucket: 'globalidoc-cd69a.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxslBI5ASejAmu3bb6VZwBdZcP4dgNh_0',
    appId: '1:148500310293:ios:69dc6f09cff9b0d68ea11c',
    messagingSenderId: '148500310293',
    projectId: 'globalidoc-cd69a',
    storageBucket: 'globalidoc-cd69a.appspot.com',
    iosBundleId: 'com.example.globalidocDesktop.RunnerTests',
  );
}
